// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_kill_50_zombies = "CgkIhO2jjY0aEAIQBg"; // <GPGSID>
        public const string achievement_kill_100_zombies = "CgkIhO2jjY0aEAIQBw"; // <GPGSID>
        public const string achievement_kill_5_zombies = "CgkIhO2jjY0aEAIQBA"; // <GPGSID>
        public const string achievement_save_25_humans = "CgkIhO2jjY0aEAIQCg"; // <GPGSID>
        public const string achievement_kill_first_zombie = "CgkIhO2jjY0aEAIQAw"; // <GPGSID>
        public const string achievement_save_100_humans = "CgkIhO2jjY0aEAIQDA"; // <GPGSID>
        public const string achievement_kill_25_zombies = "CgkIhO2jjY0aEAIQBQ"; // <GPGSID>
        public const string achievement_save_5_humans = "CgkIhO2jjY0aEAIQCQ"; // <GPGSID>
        public const string achievement_save_first_human = "CgkIhO2jjY0aEAIQCA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIhO2jjY0aEAIQAg"; // <GPGSID>
        public const string achievement_save_50_humans = "CgkIhO2jjY0aEAIQCw"; // <GPGSID>

}

